"""Offline analysis of record logs: how much of the time-to-threshold variance is
eval noise / eval cadence / hardware speed vs. genuine learning-speed variance?

Reads every `seeds/*/eval_log.jsonl`, `train_log.jsonl` and `result.json` of
the given records (defaults: all ranked records with N >= 10) and prints a
markdown report. No GPU, no model loading.

    python scripts/analyze_threshold.py
    python scripts/analyze_threshold.py records/track_a/005_prefix_kv_compile_h100 --md docs/threshold_calibration.md
"""

from __future__ import annotations

import argparse
import json
import math
import statistics
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
THRESHOLD = 0.10
GENERATED_MARKER = "<!-- generated by scripts/analyze_threshold.py; hand-written text above this line is kept -->"
Z95 = 1.959964


@dataclass
class Eval:
    step: int
    wall_s: float
    pass_rate: float
    n: int


@dataclass
class Seed:
    record: str
    seed: int
    evals: list[Eval]
    time_to_threshold_s: float
    total_steps: int
    s_per_step: float  # inclusive wall-clock time per step up to the crossing (train + eval)
    censored: bool

    @property
    def crossing(self) -> Eval | None:
        return next((e for e in self.evals if e.pass_rate >= THRESHOLD), None)

    @property
    def before_crossing(self) -> Eval | None:
        idx = next((i for i, e in enumerate(self.evals) if e.pass_rate >= THRESHOLD), None)
        return self.evals[idx - 1] if idx else None

    @property
    def slope_per_step(self) -> float | None:
        """Pass-rate slope (fraction per step) over the last eval interval before crossing."""
        a, b = self.before_crossing, self.crossing
        if a is None or b is None or b.step == a.step:
            return None
        return (b.pass_rate - a.pass_rate) / (b.step - a.step)

    @property
    def slope_per_s(self) -> float | None:
        a, b = self.before_crossing, self.crossing
        if a is None or b is None or b.wall_s == a.wall_s:
            return None
        return (b.pass_rate - a.pass_rate) / (b.wall_s - a.wall_s)

    @property
    def longest_flat_run(self) -> int:
        """Longest run of consecutive evals with an identical pass rate (greedy decoding
        makes this a sign of a policy that is not moving)."""
        best = run = 1
        for a, b in zip(self.evals, self.evals[1:]):
            run = run + 1 if b.pass_rate == a.pass_rate else 1
            best = max(best, run)
        return best


def wilson_halfwidth(p: float, n: int, z: float = Z95) -> float:
    denom = 1 + z * z / n
    centre = (p + z * z / (2 * n)) / denom
    half = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / denom
    return max(centre + half - p, p - (centre - half))


def load_seed(record: Path, seed_dir: Path) -> Seed:
    evals = [
        Eval(step=int(row["step"]), wall_s=float(row["wall_s"]), pass_rate=float(row["pass_rate"]), n=int(row["n"]))
        for row in (json.loads(line) for line in (seed_dir / "eval_log.jsonl").read_text().splitlines() if line.strip())
    ]
    result = json.loads((seed_dir / "result.json").read_text())
    ttt = result.get("time_to_threshold_s")
    steps = int(result["total_steps"])
    train = [json.loads(line) for line in (seed_dir / "train_log.jsonl").read_text().splitlines() if line.strip()]
    crossing_step = next((e.step for e in evals if e.pass_rate >= THRESHOLD), steps)
    wall_at_crossing = ttt if ttt is not None else float(train[-1]["wall_s"])
    return Seed(
        record=record.name,
        seed=int(seed_dir.name),
        evals=evals,
        time_to_threshold_s=float(ttt) if ttt is not None else math.nan,
        total_steps=steps,
        s_per_step=wall_at_crossing / crossing_step,
        censored=ttt is None,
    )


def load_record(record: Path) -> list[Seed]:
    seeds = sorted((p for p in (record / "seeds").iterdir() if p.is_dir() and p.name.isdigit()), key=lambda p: int(p.name))
    return [load_seed(record, s) for s in seeds]


def _mean_sd(xs: list[float]) -> tuple[float, float]:
    return statistics.mean(xs), (statistics.stdev(xs) if len(xs) > 1 else 0.0)


def _pct(x: float) -> str:
    return f"{100 * x:.2f} pp"


def analyze(seeds: list[Seed]) -> list[str]:
    """Return markdown lines for one record."""
    name = seeds[0].record
    out = [f"## {name}", ""]
    crossed = [s for s in seeds if not s.censored and s.crossing is not None]
    if not crossed:
        return out + ["no seed crossed the threshold", ""]

    n_eval = crossed[0].crossing.n if crossed[0].crossing else 2000
    hw = wilson_halfwidth(THRESHOLD, n_eval)
    eval_every = statistics.median(b.step - a.step for s in crossed for a, b in zip(s.evals, s.evals[1:])) if any(
        len(s.evals) > 1 for s in crossed
    ) else math.nan

    times = [s.time_to_threshold_s for s in crossed]
    steps = [float(s.crossing.step) for s in crossed if s.crossing]
    sps = [s.s_per_step for s in crossed]
    t_mean, t_sd = _mean_sd(times)
    st_mean, st_sd = _mean_sd(steps)
    sps_mean, sps_sd = _mean_sd(sps)

    # Variance decomposition: t = steps * s_per_step  =>  CV(t)^2 ~ CV(steps)^2 + CV(sps)^2 (independent, first order)
    cv_t = t_sd / t_mean
    cv_steps = st_sd / st_mean
    cv_sps = sps_sd / sps_mean

    slopes_step = [s.slope_per_step for s in crossed if s.slope_per_step is not None]
    slopes_s = [s.slope_per_s for s in crossed if s.slope_per_s is not None]
    pos_slopes_s = [x for x in slopes_s if x > 0]
    # Eval noise -> timing noise: +-hw in pass rate at slope v (fraction/s) is +-hw/v seconds.
    noise_s = [hw / v for v in pos_slopes_s]
    overshoot = [s.crossing.pass_rate - THRESHOLD for s in crossed if s.crossing]
    ambiguous = [s for s in crossed if s.crossing and s.crossing.pass_rate - hw < THRESHOLD]
    # Sanity: if the eval had been run exactly at the true crossing, how much earlier would the clock
    # have stopped? Bounded by one eval interval; the discrete cadence adds U(0, eval_every) steps.
    cadence_s = [(s.crossing.wall_s - s.before_crossing.wall_s) for s in crossed if s.crossing and s.before_crossing]
    flat = [s.longest_flat_run for s in seeds]

    out += [
        f"Seeds: {len(seeds)} ({len(crossed)} crossed, {len(seeds) - len(crossed)} censored). "
        f"Eval every ~{eval_every:.0f} steps on n = {n_eval}; Wilson 95 % half-width at p = 0.10 is ±{_pct(hw)}.",
        "",
        "| quantity | mean ± sd | CV |",
        "|---|---:|---:|",
        f"| time to threshold (s) | {t_mean:.1f} ± {t_sd:.1f} | {cv_t:.2f} |",
        f"| steps to threshold | {st_mean:.0f} ± {st_sd:.0f} | {cv_steps:.2f} |",
        f"| inclusive s/step up to crossing | {sps_mean:.3f} ± {sps_sd:.3f} | {cv_sps:.3f} |",
        "",
        f"Variance decomposition (`CV² ≈ CV²_steps + CV²_speed`): steps-to-threshold explains "
        f"{100 * cv_steps**2 / (cv_steps**2 + cv_sps**2):.0f} % of the time variance, host speed "
        f"{100 * cv_sps**2 / (cv_steps**2 + cv_sps**2):.0f} %.",
        "",
        "### Learning-curve slope at the threshold",
        "",
        "| seed | prev eval | crossing eval | Δstep | slope (pp / 100 steps) | slope (pp / min) | eval-noise → time noise (±s) |",
        "|--:|--:|--:|--:|--:|--:|--:|",
    ]
    for s in crossed:
        a, b = s.before_crossing, s.crossing
        if a is None or b is None:
            out.append(f"| {s.seed} | – | {b.pass_rate:.4f} @ {b.step} | – | – | – | – |")
            continue
        v_step = s.slope_per_step or 0.0
        v_s = s.slope_per_s or 0.0
        noise = f"±{hw / v_s:.0f}" if v_s > 0 else "∞ (flat)"
        out.append(
            f"| {s.seed} | {a.pass_rate:.4f} @ {a.step} | {b.pass_rate:.4f} @ {b.step} | {b.step - a.step} | "
            f"{100 * 100 * v_step:.2f} | {100 * 60 * v_s:.2f} | {noise} |"
        )
    med_slope_step = statistics.median(slopes_step) if slopes_step else math.nan
    med_slope_s = statistics.median(slopes_s) if slopes_s else math.nan
    med_noise = statistics.median(noise_s) if noise_s else math.nan
    out += [
        "",
        f"Median slope over the last eval interval: {100 * 100 * med_slope_step:.2f} pp / 100 steps "
        f"= {100 * 60 * med_slope_s:.2f} pp / min. At that slope the ±{_pct(hw)} eval sampling error alone "
        f"moves the crossing time by ±{med_noise:.0f} s (median over seeds; per-seed column above), "
        f"vs. an observed seed sd of {t_sd:.0f} s.",
        f"Eval cadence: crossings are only observed every {statistics.mean(cadence_s):.0f} s on average, "
        f"so the clock quantisation adds up to that much (mean ~half) per seed.",
        f"Overshoot at the crossing eval: mean {_pct(statistics.mean(overshoot))}, max {_pct(max(overshoot))}. "
        f"{len(ambiguous)}/{len(crossed)} crossing evals have their Wilson 95 % interval straddling 0.10, i.e. the "
        f"'crossing' is not statistically distinguishable from being just below threshold.",
        f"Longest run of byte-identical consecutive eval pass rates per seed: {flat} — runs ≥ 3 are stalls where "
        f"greedy outputs did not change for ≥ {2 * eval_every:.0f} steps.",
        "",
    ]

    # Counterfactual lower thresholds (only ones we can observe: runs stop at 10 %).
    out += [
        "### Counterfactual thresholds (same logs; runs stopped at 10 %, evals start at `eval_start_step`)",
        "",
        "| threshold | seeds crossed | already ≥ thr at first eval | time (s) mean ± sd | CV | steps mean |",
        "|--:|--:|--:|--:|--:|--:|",
    ]
    for thr in (0.05, 0.06, 0.07, 0.08, 0.09, 0.10):
        xs, st, at_first = [], [], 0
        for s in seeds:
            e = next((e for e in s.evals if e.pass_rate >= thr), None)
            if e is not None:
                xs.append(e.wall_s)
                st.append(e.step)
                at_first += e is s.evals[0]
        if len(xs) >= 2:
            m, sd = _mean_sd(xs)
            out.append(
                f"| {thr:.2f} | {len(xs)}/{len(seeds)} | {at_first} | {m:.0f} ± {sd:.0f} | {sd / m:.2f} | {statistics.mean(st):.0f} |"
            )
    out += [
        "",
        "Rows where most seeds are already above the threshold at the first eval are lower bounds set by",
        "`eval_start_step`, not by learning speed.",
        "",
    ]
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("records", nargs="*", type=Path, help="record directories (default: ranked records with >= 10 seeds)")
    ap.add_argument("--md", type=Path, help="also write the report to this markdown file")
    args = ap.parse_args()

    records = args.records
    if not records:
        records = [
            r
            for r in sorted((ROOT / "records" / "track_a").iterdir())
            if (r / "seeds").is_dir() and len([p for p in (r / "seeds").iterdir() if p.name.isdigit()]) >= 10
        ]
    lines = [
        GENERATED_MARKER,
        "",
        "Question: at the current 10 % threshold, how much of the seed-to-seed spread in time-to-threshold is",
        "measurement (eval sampling noise, eval cadence, host speed) and how much is the RL run genuinely learning",
        "at different speeds?",
        "",
    ]
    for record in records:
        lines += analyze(load_record(record))
    text = "\n".join(lines)
    print(text)
    if args.md:
        args.md.parent.mkdir(parents=True, exist_ok=True)
        preamble = ""
        if args.md.is_file():
            existing = args.md.read_text(encoding="utf-8")
            if GENERATED_MARKER in existing:
                preamble = existing.split(GENERATED_MARKER, 1)[0]
        args.md.write_text(preamble + text + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
